image: python:3.9

stages:
  - test
  - build
  - deploy

before_script:
  - python --version
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python -m unittest discover tests

build:
  stage: build
  script:
    - echo "Building the application"
    - python src/app.py

deploy:
  stage: deploy
  script:
    - echo "Deploying the application"
  only:
    - main
